spring:
  profiles:
    active: test

---

spring:
  profiles: test
  datasource:
    url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false
    username: sa
    password:
    driver-class-name: org.h2.Driver
    platform: h2
    initialize: true

---

spring:
  profiles: development
  datasource:
    url: jdbc:mysql://localhost/test
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver
    platform: mysql
    initialize: true
